apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: nsq-metrics
spec:
  endpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      app: nsq-metrics
